export const pieniadzeTools = [
  {
    id: 'brutto-netto',
    title: 'Brutto → netto',
    description: 'Rozłóż cenę końcową na kwotę netto i VAT.',
    category: 'VAT',
    symbol: 'B→N',
  },
  {
    id: 'netto-brutto',
    title: 'Netto → brutto',
    description: 'Dolicz VAT do ceny netto i sprawdź kwotę do zapłaty.',
    category: 'VAT',
    symbol: 'N→B',
  },
  {
    id: 'procent-z-liczby',
    title: 'Procent z liczby',
    description: 'Policz wybrany procent kwoty, ceny lub budżetu.',
    category: 'Procenty',
    symbol: '%',
  },
  {
    id: 'zmiana-procentowa',
    title: 'Zmiana procentowa',
    description: 'Sprawdź, jak bardzo wzrosła lub spadła wartość.',
    category: 'Procenty',
    symbol: '↗%',
  },
  {
    id: 'rabat',
    title: 'Rabat',
    description: 'Zobacz cenę po obniżce i realną kwotę oszczędności.',
    category: 'Zakupy',
    symbol: '−%',
  },
  {
    id: 'podwyzka',
    title: 'Podwyżka',
    description: 'Oblicz nową kwotę po procentowym zwiększeniu.',
    category: 'Procenty',
    symbol: '+%',
  },
  {
    id: 'marza',
    title: 'Marża',
    description: 'Sprawdź, jaką część ceny sprzedaży stanowi zysk.',
    category: 'Biznes',
    symbol: 'M%',
  },
  {
    id: 'narzut',
    title: 'Narzut',
    description: 'Porównaj zysk z kosztem zakupu produktu.',
    category: 'Biznes',
    symbol: 'N%',
  },
  {
    id: 'cena-jednostkowa',
    title: 'Cena jednostkowa',
    description: 'Porównaj opakowania po cenie za kilogram, litr lub sztukę.',
    category: 'Zakupy',
    symbol: 'zł/kg',
  },
  {
    id: 'podzial-rachunku',
    title: 'Podział rachunku',
    description: 'Podziel wspólny wydatek równo między osoby.',
    category: 'Na co dzień',
    symbol: '÷',
  },
  {
    id: 'napiwek',
    title: 'Napiwek',
    description: 'Dodaj procent napiwku i poznaj końcowy rachunek.',
    category: 'Na co dzień',
    symbol: '+zł',
  },
] as const
export type PieniadzeToolId = (typeof pieniadzeTools)[number]['id']
export const pieniadzeModule = {
  name: 'Pieniądze',
  description: 'Praktyczne kalkulatory do codziennych obliczeń finansowych.',
  tools: pieniadzeTools.map((tool) => ({ ...tool, to: `/pieniadze/${tool.id}` })),
}
