<script setup lang="ts">
import { ArrowUpRight, Clock3 } from '@lucide/vue'
import { RouterLink } from 'vue-router'
import { czasTools } from '../manifest'
import { czasPath, czasSiteUrl, useCzasSeo } from '../seo/useCzasSeo'
import FaqSection from '@/shared/components/FaqSection.vue'
const faq = [{ question: 'Jak liczona jest różnica między datami?', answer: 'Kalkulator porównuje wybrane daty kalendarzowe i pokazuje liczbę pełnych dni między nimi.' }, { question: 'Czy kalkulatory działają na telefonie?', answer: 'Tak. Wszystkie obliczenia wykonują się w przeglądarce na komputerze i telefonie.' }, { question: 'Czy data końcowa może być wcześniejsza?', answer: 'Tak. Kalkulator pokaże różnicę bezwzględną lub informację o dacie wcześniejszej zależnie od narzędzia.' }]
useCzasSeo('home', { '@context': 'https://schema.org', '@graph': [{ '@type': 'WebSite', name: 'Czas — kalkulatory dat i godzin', url: czasSiteUrl, inLanguage: 'pl-PL' }, { '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) }] })
</script>
<template><div><section class="bg-[#4b3d92] text-white"><div class="mx-auto max-w-7xl px-5 py-16 sm:py-24 lg:px-8"><p class="inline-flex items-center gap-2 rounded-full border border-white/20 px-3 py-1.5 text-sm text-violet-100"><Clock3 class="size-4"/> Kalkulatory czasu</p><h1 class="mt-6 max-w-3xl text-4xl font-bold sm:text-6xl">Policz czas <span class="text-[#e9ddff]">bez zgadywania</span></h1><p class="mt-5 max-w-2xl text-lg leading-8 text-white/75">Daty, wiek, godziny pracy, minuty i odliczanie do ważnego wydarzenia.</p></div></section><section class="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p class="text-sm font-bold uppercase tracking-[.16em] text-[#6555a5]">Narzędzia</p><h2 class="mt-3 text-3xl font-bold">Wybierz kalkulator</h2><div class="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3"><RouterLink v-for="tool in czasTools" :key="tool.id" :to="czasPath(`/${tool.id}`)" class="group flex min-h-52 flex-col rounded-2xl border border-[#e3dff2] bg-white p-6 transition hover:-translate-y-1 hover:shadow-xl"><Clock3 class="size-6 text-[#6555a5]"/><h3 class="mt-5 text-xl font-bold">{{ tool.title }}</h3><p class="mt-3 flex-1 text-sm leading-6 text-[#6b6682]">{{ tool.description }}</p><span class="mt-5 inline-flex items-center gap-1 font-semibold text-[#4b3d92]">Otwórz kalkulator <ArrowUpRight class="size-4"/></span></RouterLink></div><FaqSection :items="faq" title="Pytania o daty i czas"/></section></div></template>
