import type { CzasToolId } from '../manifest'
export const czasSeoContent: Record<CzasToolId, { intro: string; how: string; faqs: Array<{ question: string; answer: string }> }> = {
  'roznica-miedzy-datami': { intro: 'Kalkulator różnicy między datami pomaga obliczyć liczbę dni dzielących dwa wydarzenia. Przydaje się przy planowaniu urlopu, terminów umów, dostaw i projektów.', how: 'Daty są porównywane jako dni kalendarzowe. Kalkulator uwzględnia różną długość miesięcy oraz lata przestępne.', faqs: [{ question: 'Jak policzyć dni między dwiema datami?', answer: 'Wybierz datę początkową i końcową. Kalkulator pokaże liczbę pełnych dni między nimi.' }, { question: 'Czy kolejność dat ma znaczenie?', answer: 'Nie. Narzędzie pokazuje bezwzględną różnicę dni, dlatego działa także wtedy, gdy data końcowa jest wcześniejsza.' }] },
  'data-za-liczbe-dni': { intro: 'Kalkulator daty za określoną liczbę dni wyznacza przyszły termin po dodaniu dni do daty początkowej. Przydaje się przy planowaniu wyjazdów, płatności i wydarzeń.', how: 'Data początkowa jest dniem 0. Dodajemy pełne dni kalendarzowe, także soboty i niedziele. Wynik automatycznie uwzględnia końce miesięcy i lat.', faqs: [{ question: 'Jak obliczyć datę za 30 dni?', answer: 'Wybierz datę początkową, wpisz 30 i odczytaj datę końcową. Dla zera wynik będzie taki sam jak data początkowa.' }, { question: 'Czy kalkulator uwzględnia luty i rok przestępny?', answer: 'Tak. Operacje są wykonywane na rzeczywistym kalendarzu, dlatego długość miesiąca i lata przestępne są uwzględnione.' }, { question: 'Czy weekendy są wliczane?', answer: 'Tak. Kalkulator dodaje dni kalendarzowe, więc nie pomija sobót, niedziel ani świąt.' }] },
  wiek: { intro: 'Kalkulator wieku oblicza liczbę ukończonych lat na podstawie daty urodzenia. Dodatkowo pokazuje orientacyjną liczbę dni, które minęły od urodzenia.', how: 'Wiek jest liczony względem dzisiejszej daty. Jeśli tegoroczne urodziny jeszcze nie nastąpiły, kalkulator odejmuje jeden rok.', faqs: [{ question: 'Jak dokładnie obliczany jest wiek?', answer: 'Od bieżącego roku odejmowany jest rok urodzenia, a następnie sprawdzane jest, czy w tym roku były już urodziny.' }, { question: 'Czy mogę policzyć wiek na inną datę?', answer: 'Ten kalkulator pokazuje wiek na dziś. Do obliczenia wieku w przeszłości lub przyszłości użyj różnicy między datami.' }] },
  'czas-pracy': { intro: 'Kalkulator czasu pracy oblicza liczbę godzin i minut między rozpoczęciem a zakończeniem zmiany. Sprawdza się przy ewidencji czasu, planowaniu grafiku i kontroli nadgodzin.', how: 'Godzina zakończenia jest odejmowana od godziny rozpoczęcia. Jeśli zmiana kończy się po północy, kalkulator traktuje ją jako pracę następnego dnia.', faqs: [{ question: 'Jak policzyć czas pracy przez północ?', answer: 'Wpisz rzeczywistą godzinę rozpoczęcia i zakończenia. Gdy koniec jest wcześniejszy niż początek, kalkulator doda dobę.' }, { question: 'Czy kalkulator odlicza przerwę?', answer: 'Nie. Aby uwzględnić przerwę, odejmij jej długość od otrzymanego wyniku.' }] },
  'godziny-na-minuty': { intro: 'Kalkulator godziny na minuty przelicza dowolną liczbę godzin na minuty. Jest przydatny przy rozliczaniu czasu pracy, nauki, treningu i projektów.', how: 'Jedna godzina to 60 minut, dlatego liczbę godzin mnożymy przez 60.', faqs: [{ question: 'Ile minut ma 2,5 godziny?', answer: '2,5 godziny to 150 minut, ponieważ 2,5 należy pomnożyć przez 60.' }, { question: 'Czy można wpisywać godziny dziesiętne?', answer: 'Tak. Kalkulator obsługuje wartości dziesiętne, na przykład 1,5 godziny.' }] },
  'minuty-na-godziny': { intro: 'Kalkulator minuty na godziny pokazuje liczbę pełnych godzin oraz pozostałe minuty. Ułatwia czytelne zapisywanie długiego czasu w formacie godzinowym.', how: 'Liczba minut jest dzielona przez 60. Część całkowita to godziny, a reszta z dzielenia to pozostałe minuty.', faqs: [{ question: 'Ile to 135 minut w godzinach?', answer: '135 minut to 2 godziny i 15 minut.' }, { question: 'Jak przeliczyć minuty na godziny dziesiętne?', answer: 'Podziel liczbę minut przez 60. Na przykład 90 minut to 1,5 godziny.' }] },
  'odliczanie-do-daty': { intro: 'Kalkulator odliczania do daty pokazuje liczbę dni pozostałych do wydarzenia. Możesz użyć go do planowania urodzin, urlopu, terminu projektu lub ważnej płatności.', how: 'Wybrana data wydarzenia jest porównywana z dzisiejszą datą kalendarzową, a wynik jest podawany w pełnych dniach.', faqs: [{ question: 'Jak sprawdzić ile dni zostało do wydarzenia?', answer: 'Wybierz datę wydarzenia. Kalkulator automatycznie pokaże liczbę dni względem dzisiejszej daty.' }, { question: 'Czy wynik zmienia się każdego dnia?', answer: 'Tak. Odliczanie jest liczone od bieżącej daty, dlatego po otwarciu strony kolejnego dnia wynik będzie aktualny.' }] },
}
