<script setup lang="ts">
import { ArrowUpRight, BriefcaseBusiness, Scale, Wallet } from '@lucide/vue'
import { RouterLink } from 'vue-router'
import { pracaPath, pracaSiteName, pracaSiteUrl, usePracaSeo } from '../seo/usePracaSeo'
import FaqSection from '@/shared/components/FaqSection.vue'
const tools = [
  { path: '/ile-na-reke-uop', icon: BriefcaseBusiness, tag: 'Umowa o pracę', title: 'Ile na rękę z UoP?', text: 'Przelicz brutto na netto, zobacz składki i koszt pracodawcy.' },
  { path: '/ile-na-reke-b2b', icon: Wallet, tag: 'Działalność gospodarcza', title: 'Ile zostaje z faktury B2B?', text: 'Uwzględnij podatek, koszty firmy i wariant ZUS.' },
  { path: '/b2b-vs-uop', icon: Scale, tag: 'Porównanie ofert', title: 'B2B czy UoP — co się opłaca?', text: 'Zestaw dwie propozycje i zobacz różnicę w dochodzie.' },
]
const faq = [
  { question: 'Czym różni się wynagrodzenie brutto od netto?', answer: 'Wynagrodzenie brutto to kwota zapisana w umowie przed potrąceniami. Wynagrodzenie netto, czyli „na rękę”, jest kwotą otrzymywaną po odjęciu składek ZUS, składki zdrowotnej oraz zaliczki na podatek dochodowy.' },
  { question: 'Jak obliczyć wynagrodzenie netto z umowy o pracę?', answer: 'Aby obliczyć pensję netto z UoP, potrzebujesz przede wszystkim miesięcznej kwoty brutto. Na wynik wpływają też koszty uzyskania przychodu, PIT-2, ulga dla młodych, PPK oraz indywidualne ulgi podatkowe. Kalkulator brutto-netto pokazuje uproszczony podział tych elementów.' },
  { question: 'Co oznacza całkowity koszt pracodawcy?', answer: 'Koszt pracodawcy jest wyższy niż pensja brutto pracownika, ponieważ obejmuje również składki finansowane przez pracodawcę. Przy porównywaniu oferty UoP z B2B warto patrzeć zarówno na kwotę netto, jak i na całkowity budżet firmy.' },
  { question: 'Czy faktura B2B jest porównywalna z pensją brutto?', answer: 'Nie bezpośrednio. Z faktury B2B przedsiębiorca opłaca podatek, składki ZUS, składkę zdrowotną i koszty działalności. W porównaniu B2B vs UoP warto uwzględnić również księgowość, płatny urlop, chorobowe, benefity i ryzyko przerw w zleceniach.' },
  { question: 'Jaka forma opodatkowania B2B będzie najlepsza?', answer: 'Skala podatkowa, podatek liniowy i ryczałt różnią się sposobem liczenia podatku oraz możliwością rozliczania kosztów. Najkorzystniejszy wariant zależy od przychodu, kosztów, stawki ryczałtu, ulg i sytuacji rodzinnej, dlatego warto porównać kilka scenariuszy.' },
  { question: 'Czy wyniki kalkulatorów są wiążące?', answer: 'Nie. Kalkulatory wynagrodzeń pomagają oszacować wypłatę i porównać oferty, ale nie zastępują indywidualnego rozliczenia. Ostateczna kwota może zależeć od limitów rocznych, dodatkowych przychodów, ulg i aktualnych przepisów.' },
]
usePracaSeo('home', { '@context': 'https://schema.org', '@graph': [{ '@type': 'Organization', name: pracaSiteName, url: pracaSiteUrl }, { '@type': 'WebSite', name: pracaSiteName, url: pracaSiteUrl, inLanguage: 'pl-PL' }, { '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) }] })
</script>
<template><div><section class="overflow-hidden bg-[#123b2d] text-white"><div class="mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 sm:py-24 lg:grid-cols-[1.05fr_.95fr] lg:px-8"><div><p class="inline-flex rounded-full border border-white/20 px-3 py-1.5 text-sm text-emerald-100">Kalkulatory wynagrodzeń</p><h1 class="mt-6 max-w-2xl text-4xl font-bold leading-tight tracking-tight sm:text-6xl">Zobacz, ile naprawdę dostaniesz <span class="text-[#9fe1b8]">na rękę</span></h1><p class="mt-5 max-w-xl text-lg leading-8 text-white/75">Przelicz wynagrodzenie UoP i B2B, poznaj składki oraz porównaj oferty pracy na konkretnych liczbach.</p><RouterLink :to="pracaPath('/b2b-vs-uop')" class="mt-8 inline-flex items-center gap-2 rounded-lg bg-[#a9e4bd] px-5 py-3 font-semibold text-[#123b2d]">Porównaj B2B i UoP <ArrowUpRight class="size-4" /></RouterLink></div><div class="rounded-3xl border border-white/15 bg-white/[.07] p-6 shadow-2xl sm:p-8"><p class="text-sm text-emerald-100">Twoja pensja, w prostym podziale</p><div class="mt-6 border-b border-white/15 pb-5"><p class="text-sm text-white/65">Kwota brutto</p><p class="mt-1 text-2xl font-semibold">12 000 zł</p></div><div class="space-y-3 py-5 text-sm text-white/75"><div class="flex justify-between"><span>Składki ZUS</span><span>− 1 645 zł</span></div><div class="flex justify-between"><span>Składka zdrowotna</span><span>− 932 zł</span></div><div class="flex justify-between"><span>Zaliczka PIT</span><span>− 778 zł</span></div></div><div class="rounded-2xl bg-[#a9e4bd] p-5 text-[#123b2d]"><span>Na rękę</span><strong class="float-right text-xl">sprawdź wynik</strong></div></div></div></section><section class="mx-auto max-w-7xl px-5 py-16 sm:py-20 lg:px-8"><p class="text-sm font-bold uppercase tracking-[.16em] text-[#25815c]">Narzędzia</p><h2 class="mt-3 text-3xl font-bold">Wybierz kalkulator</h2><div class="mt-8 grid gap-5 md:grid-cols-3"><RouterLink v-for="tool in tools" :key="tool.path" :to="pracaPath(tool.path)" class="group flex min-h-64 flex-col rounded-2xl border border-[#e1e7e2] bg-white p-6 transition hover:-translate-y-1 hover:shadow-xl"><component :is="tool.icon" class="size-7 text-[#17613f]" /><p class="mt-6 text-xs font-bold uppercase tracking-wider text-[#25815c]">{{ tool.tag }}</p><h3 class="mt-2 text-xl font-bold">{{ tool.title }}</h3><p class="mt-3 flex-1 text-sm leading-6 text-[#66736b]">{{ tool.text }}</p><span class="mt-5 font-semibold text-[#17613f]">Otwórz kalkulator →</span></RouterLink></div><FaqSection :items="faq" title="Jak działają kalkulatory wynagrodzeń?" /></section></div></template>
