import type { PieniadzeToolId } from '../manifest'

export interface ToolSeoContent { intro: string; howItWorks: string; faqs: Array<{ question: string; answer: string }> }
export const toolSeoContent: Record<PieniadzeToolId, ToolSeoContent> = {
  'brutto-netto': { intro: 'Kalkulator brutto netto VAT pozwala szybko rozłożyć cenę końcową na kwotę netto i podatek VAT. Jest przydatny przy sprawdzaniu faktur, ofert oraz cen produktów.', howItWorks: 'Kwota netto powstaje przez podzielenie ceny brutto przez 1 powiększone o stawkę VAT. Różnica między brutto a netto to wartość VAT.', faqs: [{ question: 'Jak obliczyć VAT z kwoty brutto?', answer: 'Podziel kwotę brutto przez 1 plus stawka VAT, aby otrzymać netto. Następnie odejmij netto od brutto — otrzymasz VAT.' }, { question: 'Jaka stawka VAT jest najczęstsza?', answer: 'Podstawowa stawka VAT w Polsce wynosi 23%, ale dla wybranych produktów i usług mogą obowiązywać stawki obniżone lub zwolnienie.' }] },
  'netto-brutto': { intro: 'Kalkulator netto brutto VAT oblicza cenę końcową, gdy znasz kwotę netto. Pomaga przygotować ofertę, fakturę lub sprawdzić koszt zakupu.', howItWorks: 'Kwota brutto to kwota netto pomnożona przez 1 powiększone o wybraną stawkę VAT. VAT jest różnicą między ceną brutto i netto.', faqs: [{ question: 'Jak obliczyć brutto z netto?', answer: 'Pomnóż kwotę netto przez 1 plus stawka VAT wyrażona jako ułamek, na przykład przez 1,23 dla VAT 23%.' }, { question: 'Czy VAT zawsze dolicza się do ceny netto?', answer: 'Nie w każdej sytuacji. Sposób rozliczenia zależy od statusu sprzedawcy, rodzaju transakcji i obowiązujących przepisów.' }] },
  'procent-z-liczby': { intro: 'Kalkulator procentu z liczby oblicza część dowolnej wartości. Przydaje się przy wyliczaniu prowizji, podatku, udziału wydatku lub fragmentu budżetu.', howItWorks: 'Aby policzyć procent z liczby, mnożymy liczbę przez procent i dzielimy wynik przez 100.', faqs: [{ question: 'Jak obliczyć 20 procent z liczby?', answer: 'Pomnóż liczbę przez 20 i podziel przez 100. Ten sam wynik uzyskasz, mnożąc liczbę przez 0,2.' }, { question: 'Do czego przydaje się kalkulator procentowy?', answer: 'Można nim obliczać rabaty, prowizje, VAT, odsetki i procentowy udział jednej kwoty w drugiej.' }] },
  'zmiana-procentowa': { intro: 'Kalkulator zmiany procentowej pokazuje, o ile procent wzrosła lub spadła kwota między wartością początkową a końcową. Ułatwia analizę cen, przychodów i oszczędności.', howItWorks: 'Różnicę między kwotą końcową i początkową dzielimy przez wartość początkową, a następnie mnożymy przez 100.', faqs: [{ question: 'Jak obliczyć procentowy wzrost ceny?', answer: 'Odejmij starą cenę od nowej, podziel wynik przez starą cenę i pomnóż przez 100.' }, { question: 'Dlaczego wartość początkowa nie może wynosić zero?', answer: 'Nie można dzielić przez zero, dlatego procentowej zmiany od wartości zerowej nie da się wyliczyć standardowym wzorem.' }] },
  rabat: { intro: 'Kalkulator rabatu pokazuje, ile wynosi obniżka i ile zapłacisz po promocji. Jest pomocny podczas zakupów oraz przy planowaniu ofert sprzedażowych.', howItWorks: 'Wysokość rabatu to cena przed obniżką pomnożona przez procent rabatu. Cenę po rabacie otrzymasz po odjęciu tej wartości.', faqs: [{ question: 'Jak obliczyć cenę po rabacie?', answer: 'Pomnóż cenę wyjściową przez 1 minus procent rabatu. Dla rabatu 15% użyj mnożnika 0,85.' }, { question: 'Czy dwa rabaty sumują się?', answer: 'Nie zawsze. Kolejny rabat zwykle liczy się od ceny już obniżonej, więc wynik różni się od prostego dodania procentów.' }] },
  podwyzka: { intro: 'Kalkulator podwyżki oblicza nową kwotę po zwiększeniu ceny, pensji lub innej wartości o wskazany procent.', howItWorks: 'Kwota podwyżki to wartość wyjściowa pomnożona przez procent. Nowa wartość powstaje po dodaniu podwyżki.', faqs: [{ question: 'Jak obliczyć podwyżkę o 10 procent?', answer: 'Pomnóż pierwotną kwotę przez 0,10, a następnie dodaj wynik do pierwotnej kwoty.' }, { question: 'Czy podwyżka i rabat o ten sam procent się znoszą?', answer: 'Nie. Podwyżka i rabat są liczone od różnych podstaw, dlatego na przykład wzrost o 10% i spadek o 10% nie przywracają tej samej kwoty.' }] },
  marza: { intro: 'Kalkulator marży wylicza, jaką część ceny sprzedaży stanowi zysk. To podstawowa miara przy analizie rentowności sprzedaży.', howItWorks: 'Zysk to cena sprzedaży minus koszt zakupu. Marża procentowa to zysk podzielony przez cenę sprzedaży i pomnożony przez 100.', faqs: [{ question: 'Czym jest marża?', answer: 'Marża określa udział zysku w cenie sprzedaży. Nie jest tym samym co narzut, który odnosi zysk do kosztu zakupu.' }, { question: 'Jak obliczyć marżę procentową?', answer: 'Odejmij koszt od ceny sprzedaży, podziel zysk przez cenę sprzedaży i pomnóż przez 100.' }] },
  narzut: { intro: 'Kalkulator narzutu pokazuje, o ile procent cena sprzedaży jest wyższa od kosztu zakupu. Ułatwia ustalanie cen produktów i usług.', howItWorks: 'Narzut procentowy to zysk podzielony przez koszt zakupu, pomnożony przez 100.', faqs: [{ question: 'Czym różni się narzut od marży?', answer: 'Narzut odnosi zysk do kosztu zakupu, a marża do ceny sprzedaży. Dlatego ich wartości procentowe są różne.' }, { question: 'Jak ustalić cenę przy znanym narzucie?', answer: 'Pomnóż koszt zakupu przez 1 plus narzut wyrażony jako ułamek. Dla narzutu 30% mnożnik wynosi 1,3.' }] },
  'cena-jednostkowa': { intro: 'Kalkulator ceny jednostkowej pozwala porównać produkty o różnych opakowaniach. Oblicza cenę za kilogram, litr, metr lub sztukę.', howItWorks: 'Cenę opakowania dzielimy przez jego ilość. Niższa cena jednostkowa zwykle oznacza korzystniejszą ofertę, jeśli produkty są porównywalne.', faqs: [{ question: 'Jak porównać cenę za kilogram?', answer: 'Podziel cenę opakowania przez jego masę w kilogramach. Dla gramów najpierw przelicz masę na kilogramy.' }, { question: 'Czy większe opakowanie zawsze jest tańsze?', answer: 'Nie. Porównaj cenę jednostkową, ponieważ większe opakowanie może mieć wyższą cenę za kilogram lub litr.' }] },
  'podzial-rachunku': { intro: 'Kalkulator podziału rachunku oblicza równą kwotę dla każdej osoby. Przydaje się w restauracji, podczas wspólnego wyjazdu lub dzielenia kosztów zakupów.', howItWorks: 'Łączną kwotę rachunku dzielimy przez liczbę osób. Wynik można wykorzystać jako podstawę do rozliczenia przelewów lub płatności mobilnych.', faqs: [{ question: 'Jak podzielić rachunek po równo?', answer: 'Wpisz całkowitą kwotę oraz liczbę osób. Kalkulator pokaże kwotę przypadającą na jedną osobę.' }, { question: 'Czy kalkulator uwzględnia napiwek?', answer: 'Najpierw oblicz rachunek z napiwkiem w kalkulatorze napiwku, a następnie wpisz końcową kwotę do podziału rachunku.' }] },
  napiwek: { intro: 'Kalkulator napiwku oblicza kwotę napiwku oraz końcowy rachunek. Pomaga szybko policzyć procentową dopłatę w restauracji, salonie lub podczas dostawy.', howItWorks: 'Napiwek to wartość rachunku pomnożona przez wybrany procent. Końcowy rachunek to suma pierwotnej kwoty i napiwku.', faqs: [{ question: 'Jak obliczyć napiwek 10 procent?', answer: 'Pomnóż wartość rachunku przez 0,10. Otrzymaną kwotę dodaj do rachunku, aby poznać sumę do zapłaty.' }, { question: 'Jak podzielić rachunek z napiwkiem?', answer: 'Najpierw oblicz końcowy rachunek z napiwkiem, a następnie podziel tę kwotę przez liczbę osób.' }] },
}
