<script setup lang="ts">
import { Calculator, ArrowUpRight } from '@lucide/vue'
import { RouterLink } from 'vue-router'
import { pieniadzeTools } from '../manifest'
import { pieniadzePath, pieniadzeSiteName, pieniadzeSiteUrl, usePieniadzeSeo } from '../seo/usePieniadzeSeo'
import FaqSection from '@/shared/components/FaqSection.vue'
const faq = [{ question: 'Jak działają kalkulatory finansowe?', answer: 'Wpisz własne wartości, a wynik aktualizuje się od razu w przeglądarce. Dane nie są wysyłane na serwer.' }, { question: 'Jaką stawkę VAT wybrać?', answer: 'Wybierz stawkę właściwą dla produktu lub usługi. Najczęściej stosowana jest stawka 23%, ale w Polsce obowiązują też stawki obniżone i zwolnienia.' }, { question: 'Czym różni się marża od narzutu?', answer: 'Marża pokazuje udział zysku w cenie sprzedaży, a narzut udział zysku w koszcie zakupu. Te same kwoty dają inne wartości procentowe.' }]
usePieniadzeSeo('home', { '@context': 'https://schema.org', '@graph': [{ '@type': 'WebSite', name: pieniadzeSiteName, url: pieniadzeSiteUrl, inLanguage: 'pl-PL' }, { '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) }] })
</script>
<template><div><section class="bg-[#173b67] text-white"><div class="mx-auto max-w-7xl px-5 py-16 sm:py-24 lg:px-8"><p class="inline-flex items-center gap-2 rounded-full border border-white/20 px-3 py-1.5 text-sm text-blue-100"><Calculator class="size-4"/> Kalkulatory finansowe</p><h1 class="mt-6 max-w-3xl text-4xl font-bold tracking-tight sm:text-6xl">Policz pieniądze <span class="text-[#f8d66d]">prościej</span></h1><p class="mt-5 max-w-2xl text-lg leading-8 text-white/75">VAT, rabaty, marża, procenty i wspólne rachunki — wszystkie codzienne obliczenia w jednym miejscu.</p></div></section><section class="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p class="text-sm font-bold uppercase tracking-[.16em] text-[#24578f]">Narzędzia</p><h2 class="mt-3 text-3xl font-bold">Wybierz kalkulator</h2><div class="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3"><RouterLink v-for="tool in pieniadzeTools" :key="tool.id" :to="pieniadzePath(`/${tool.id}`)" class="group flex min-h-52 flex-col rounded-2xl border border-[#dce5f0] bg-white p-6 transition hover:-translate-y-1 hover:border-[#8cb4dc] hover:shadow-xl"><Calculator class="size-6 text-[#24578f]"/><h3 class="mt-5 text-xl font-bold">{{ tool.title }}</h3><p class="mt-3 flex-1 text-sm leading-6 text-[#64748b]">{{ tool.description }}</p><span class="mt-5 inline-flex items-center gap-1 font-semibold text-[#173b67]">Otwórz kalkulator <ArrowUpRight class="size-4"/></span></RouterLink></div><FaqSection :items="faq" title="Pytania o kalkulatory finansowe"/></section></div></template>
